### ISSUE TITLE
Uncaught ReferenceError: path is not defined

### ISSUE THREAD

**Issue by namqdam** [AtomicGameEngine/atom-editor-package#1]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.199.0
**System**: Mac OS X 10.10.3
**Thrown From**: [atomic-game-engine](https://github.com/AtomicGameEngine/atom-editor-package) package, v0.4.5
### Stack Trace

Uncaught ReferenceError: path is not defined

```
At /Users/macbookpro/.atom/packages/atomic-game-engine/lib/atomic-game-engine.coffee:67

ReferenceError: path is not defined
  at Object.module.exports.AtomicGameEngine.runCLI (/Users/macbookpro/.atom/packages/atomic-game-engine/lib/atomic-game-engine.coffee:67:16)
  at Object.module.exports.AtomicGameEngine.run (/Users/macbookpro/.atom/packages/atomic-game-engine/lib/atomic-game-engine.coffee:110:10)
  at atom-workspace.subscriptions.add.atom.commands.add.atomic-game-engine:run (/Users/macbookpro/.atom/packages/atomic-game-engine/lib/atomic-game-engine.coffee:18:90)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:153:19)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:71:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)

```
### Commands

```
     -0:00.8.0 atomic-game-engine:run (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```
### Config

``` json
{
  "core": {
    "audioBeep": false,
    "themes": [
      "isotope-ui",
      "one-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
.bin, vundefined
atom-typescript, v4.3.1
atomic-game-engine, v0.4.5
autocomplete-haxe, v0.2.0
color-picker, v1.7.0
isotope-ui, v2.2.1
linter, v0.12.2

# Dev
No dev packages
```

**Comment by lewislepton** [comment]
i have that same problem actually. doesnt run or open from atom

**Comment by JoshEngebretson** [comment]
Have you run the cli from the command line and activated?

**Comment by lewislepton** [comment]
yeah. made sure that was working

**Comment by lewislepton** [comment]
i have tried again on a clean install. but still this problem

i do the terminal, activate it. it asks for the agreement. i say yes. also my licence, wihch i enter. activates fine. then this error pops up when in atom
